/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SafeguardingRouteImport } from './routes/safeguarding'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PracticumsRouteImport } from './routes/practicums'
import { Route as HpiAssessmentRouteImport } from './routes/hpi-assessment'
import { Route as HowHpiWorksRouteImport } from './routes/how-hpi-works'
import { Route as HomeDemoRouteImport } from './routes/home-demo'
import { Route as GrowWithUsRouteImport } from './routes/grow-with-us'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticumsStartupLabCampRouteImport } from './routes/practicums_.startup-lab-camp'
import { Route as PracticumsMiraeIndustryRouteImport } from './routes/practicums_.mirae-industry'
import { Route as PracticumsHanaroMarketingRouteImport } from './routes/practicums_.hanaro-marketing'
import { Route as PracticumsHanaroRouteImport } from './routes/practicums_.hanaro'
import { Route as EventsLaunchEventRouteImport } from './routes/events_.launch-event'
import { Route as AboutPartnershipsRouteImport } from './routes/about_.partnerships'
import { Route as AboutOurStoryRouteImport } from './routes/about_.our-story'
import { Route as PracticumsHanaroMarketingVoicesInMotionRouteImport } from './routes/practicums_.hanaro-marketing_.voices-in-motion'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeguardingRoute = SafeguardingRouteImport.update({
  id: '/safeguarding',
  path: '/safeguarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticumsRoute = PracticumsRouteImport.update({
  id: '/practicums',
  path: '/practicums',
  getParentRoute: () => rootRouteImport,
} as any)
const HpiAssessmentRoute = HpiAssessmentRouteImport.update({
  id: '/hpi-assessment',
  path: '/hpi-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const HowHpiWorksRoute = HowHpiWorksRouteImport.update({
  id: '/how-hpi-works',
  path: '/how-hpi-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeDemoRoute = HomeDemoRouteImport.update({
  id: '/home-demo',
  path: '/home-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowWithUsRoute = GrowWithUsRouteImport.update({
  id: '/grow-with-us',
  path: '/grow-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticumsStartupLabCampRoute =
  PracticumsStartupLabCampRouteImport.update({
    id: '/practicums_/startup-lab-camp',
    path: '/practicums/startup-lab-camp',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticumsMiraeIndustryRoute = PracticumsMiraeIndustryRouteImport.update({
  id: '/practicums_/mirae-industry',
  path: '/practicums/mirae-industry',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticumsHanaroMarketingRoute =
  PracticumsHanaroMarketingRouteImport.update({
    id: '/practicums_/hanaro-marketing',
    path: '/practicums/hanaro-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticumsHanaroRoute = PracticumsHanaroRouteImport.update({
  id: '/practicums_/hanaro',
  path: '/practicums/hanaro',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsLaunchEventRoute = EventsLaunchEventRouteImport.update({
  id: '/events_/launch-event',
  path: '/events/launch-event',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPartnershipsRoute = AboutPartnershipsRouteImport.update({
  id: '/about_/partnerships',
  path: '/about/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOurStoryRoute = AboutOurStoryRouteImport.update({
  id: '/about_/our-story',
  path: '/about/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticumsHanaroMarketingVoicesInMotionRoute =
  PracticumsHanaroMarketingVoicesInMotionRouteImport.update({
    id: '/practicums_/hanaro-marketing_/voices-in-motion',
    path: '/practicums/hanaro-marketing/voices-in-motion',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/events': typeof EventsRoute
  '/grow-with-us': typeof GrowWithUsRoute
  '/home-demo': typeof HomeDemoRoute
  '/how-hpi-works': typeof HowHpiWorksRoute
  '/hpi-assessment': typeof HpiAssessmentRoute
  '/practicums': typeof PracticumsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/safeguarding': typeof SafeguardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/about/partnerships': typeof AboutPartnershipsRoute
  '/events/launch-event': typeof EventsLaunchEventRoute
  '/practicums/hanaro': typeof PracticumsHanaroRoute
  '/practicums/hanaro-marketing': typeof PracticumsHanaroMarketingRoute
  '/practicums/mirae-industry': typeof PracticumsMiraeIndustryRoute
  '/practicums/startup-lab-camp': typeof PracticumsStartupLabCampRoute
  '/practicums/hanaro-marketing/voices-in-motion': typeof PracticumsHanaroMarketingVoicesInMotionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/events': typeof EventsRoute
  '/grow-with-us': typeof GrowWithUsRoute
  '/home-demo': typeof HomeDemoRoute
  '/how-hpi-works': typeof HowHpiWorksRoute
  '/hpi-assessment': typeof HpiAssessmentRoute
  '/practicums': typeof PracticumsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/safeguarding': typeof SafeguardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/about/partnerships': typeof AboutPartnershipsRoute
  '/events/launch-event': typeof EventsLaunchEventRoute
  '/practicums/hanaro': typeof PracticumsHanaroRoute
  '/practicums/hanaro-marketing': typeof PracticumsHanaroMarketingRoute
  '/practicums/mirae-industry': typeof PracticumsMiraeIndustryRoute
  '/practicums/startup-lab-camp': typeof PracticumsStartupLabCampRoute
  '/practicums/hanaro-marketing/voices-in-motion': typeof PracticumsHanaroMarketingVoicesInMotionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/events': typeof EventsRoute
  '/grow-with-us': typeof GrowWithUsRoute
  '/home-demo': typeof HomeDemoRoute
  '/how-hpi-works': typeof HowHpiWorksRoute
  '/hpi-assessment': typeof HpiAssessmentRoute
  '/practicums': typeof PracticumsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/safeguarding': typeof SafeguardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/about_/our-story': typeof AboutOurStoryRoute
  '/about_/partnerships': typeof AboutPartnershipsRoute
  '/events_/launch-event': typeof EventsLaunchEventRoute
  '/practicums_/hanaro': typeof PracticumsHanaroRoute
  '/practicums_/hanaro-marketing': typeof PracticumsHanaroMarketingRoute
  '/practicums_/mirae-industry': typeof PracticumsMiraeIndustryRoute
  '/practicums_/startup-lab-camp': typeof PracticumsStartupLabCampRoute
  '/practicums_/hanaro-marketing_/voices-in-motion': typeof PracticumsHanaroMarketingVoicesInMotionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/connect'
    | '/events'
    | '/grow-with-us'
    | '/home-demo'
    | '/how-hpi-works'
    | '/hpi-assessment'
    | '/practicums'
    | '/privacy'
    | '/refund-policy'
    | '/safeguarding'
    | '/sitemap.xml'
    | '/terms'
    | '/about/our-story'
    | '/about/partnerships'
    | '/events/launch-event'
    | '/practicums/hanaro'
    | '/practicums/hanaro-marketing'
    | '/practicums/mirae-industry'
    | '/practicums/startup-lab-camp'
    | '/practicums/hanaro-marketing/voices-in-motion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/connect'
    | '/events'
    | '/grow-with-us'
    | '/home-demo'
    | '/how-hpi-works'
    | '/hpi-assessment'
    | '/practicums'
    | '/privacy'
    | '/refund-policy'
    | '/safeguarding'
    | '/sitemap.xml'
    | '/terms'
    | '/about/our-story'
    | '/about/partnerships'
    | '/events/launch-event'
    | '/practicums/hanaro'
    | '/practicums/hanaro-marketing'
    | '/practicums/mirae-industry'
    | '/practicums/startup-lab-camp'
    | '/practicums/hanaro-marketing/voices-in-motion'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/connect'
    | '/events'
    | '/grow-with-us'
    | '/home-demo'
    | '/how-hpi-works'
    | '/hpi-assessment'
    | '/practicums'
    | '/privacy'
    | '/refund-policy'
    | '/safeguarding'
    | '/sitemap.xml'
    | '/terms'
    | '/about_/our-story'
    | '/about_/partnerships'
    | '/events_/launch-event'
    | '/practicums_/hanaro'
    | '/practicums_/hanaro-marketing'
    | '/practicums_/mirae-industry'
    | '/practicums_/startup-lab-camp'
    | '/practicums_/hanaro-marketing_/voices-in-motion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConnectRoute: typeof ConnectRoute
  EventsRoute: typeof EventsRoute
  GrowWithUsRoute: typeof GrowWithUsRoute
  HomeDemoRoute: typeof HomeDemoRoute
  HowHpiWorksRoute: typeof HowHpiWorksRoute
  HpiAssessmentRoute: typeof HpiAssessmentRoute
  PracticumsRoute: typeof PracticumsRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SafeguardingRoute: typeof SafeguardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AboutOurStoryRoute: typeof AboutOurStoryRoute
  AboutPartnershipsRoute: typeof AboutPartnershipsRoute
  EventsLaunchEventRoute: typeof EventsLaunchEventRoute
  PracticumsHanaroRoute: typeof PracticumsHanaroRoute
  PracticumsHanaroMarketingRoute: typeof PracticumsHanaroMarketingRoute
  PracticumsMiraeIndustryRoute: typeof PracticumsMiraeIndustryRoute
  PracticumsStartupLabCampRoute: typeof PracticumsStartupLabCampRoute
  PracticumsHanaroMarketingVoicesInMotionRoute: typeof PracticumsHanaroMarketingVoicesInMotionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safeguarding': {
      id: '/safeguarding'
      path: '/safeguarding'
      fullPath: '/safeguarding'
      preLoaderRoute: typeof SafeguardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicums': {
      id: '/practicums'
      path: '/practicums'
      fullPath: '/practicums'
      preLoaderRoute: typeof PracticumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hpi-assessment': {
      id: '/hpi-assessment'
      path: '/hpi-assessment'
      fullPath: '/hpi-assessment'
      preLoaderRoute: typeof HpiAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-hpi-works': {
      id: '/how-hpi-works'
      path: '/how-hpi-works'
      fullPath: '/how-hpi-works'
      preLoaderRoute: typeof HowHpiWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-demo': {
      id: '/home-demo'
      path: '/home-demo'
      fullPath: '/home-demo'
      preLoaderRoute: typeof HomeDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grow-with-us': {
      id: '/grow-with-us'
      path: '/grow-with-us'
      fullPath: '/grow-with-us'
      preLoaderRoute: typeof GrowWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicums_/startup-lab-camp': {
      id: '/practicums_/startup-lab-camp'
      path: '/practicums/startup-lab-camp'
      fullPath: '/practicums/startup-lab-camp'
      preLoaderRoute: typeof PracticumsStartupLabCampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicums_/mirae-industry': {
      id: '/practicums_/mirae-industry'
      path: '/practicums/mirae-industry'
      fullPath: '/practicums/mirae-industry'
      preLoaderRoute: typeof PracticumsMiraeIndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicums_/hanaro-marketing': {
      id: '/practicums_/hanaro-marketing'
      path: '/practicums/hanaro-marketing'
      fullPath: '/practicums/hanaro-marketing'
      preLoaderRoute: typeof PracticumsHanaroMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicums_/hanaro': {
      id: '/practicums_/hanaro'
      path: '/practicums/hanaro'
      fullPath: '/practicums/hanaro'
      preLoaderRoute: typeof PracticumsHanaroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/launch-event': {
      id: '/events_/launch-event'
      path: '/events/launch-event'
      fullPath: '/events/launch-event'
      preLoaderRoute: typeof EventsLaunchEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/partnerships': {
      id: '/about_/partnerships'
      path: '/about/partnerships'
      fullPath: '/about/partnerships'
      preLoaderRoute: typeof AboutPartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/our-story': {
      id: '/about_/our-story'
      path: '/about/our-story'
      fullPath: '/about/our-story'
      preLoaderRoute: typeof AboutOurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicums_/hanaro-marketing_/voices-in-motion': {
      id: '/practicums_/hanaro-marketing_/voices-in-motion'
      path: '/practicums/hanaro-marketing/voices-in-motion'
      fullPath: '/practicums/hanaro-marketing/voices-in-motion'
      preLoaderRoute: typeof PracticumsHanaroMarketingVoicesInMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConnectRoute: ConnectRoute,
  EventsRoute: EventsRoute,
  GrowWithUsRoute: GrowWithUsRoute,
  HomeDemoRoute: HomeDemoRoute,
  HowHpiWorksRoute: HowHpiWorksRoute,
  HpiAssessmentRoute: HpiAssessmentRoute,
  PracticumsRoute: PracticumsRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SafeguardingRoute: SafeguardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AboutOurStoryRoute: AboutOurStoryRoute,
  AboutPartnershipsRoute: AboutPartnershipsRoute,
  EventsLaunchEventRoute: EventsLaunchEventRoute,
  PracticumsHanaroRoute: PracticumsHanaroRoute,
  PracticumsHanaroMarketingRoute: PracticumsHanaroMarketingRoute,
  PracticumsMiraeIndustryRoute: PracticumsMiraeIndustryRoute,
  PracticumsStartupLabCampRoute: PracticumsStartupLabCampRoute,
  PracticumsHanaroMarketingVoicesInMotionRoute:
    PracticumsHanaroMarketingVoicesInMotionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
