/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SafeguardingRouteImport } from './routes/safeguarding'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PracticumsRouteImport } from './routes/practicums'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GrowWithUsRouteImport } from './routes/grow-with-us'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticumsStartupLabCampRouteImport } from './routes/practicums_.startup-lab-camp'
import { Route as PracticumsMiraeIndustryRouteImport } from './routes/practicums_.mirae-industry'
import { Route as PracticumsHanaroRouteImport } from './routes/practicums_.hanaro'
import { Route as NewsDigitalMediaAndDroneShowTechnologyWithYanPaulDubbelmanRouteImport } from './routes/news_.digital-media-and-drone-show-technology-with-yan-paul-dubbelman'
import { Route as AboutSparkedRouteImport } from './routes/about_.sparked'
import { Route as AboutOurStoryRouteImport } from './routes/about_.our-story'
import { Route as PracticumsStartupLabCampIndexRouteImport } from './routes/practicums_.startup-lab-camp.index'
import { Route as PracticumsStartupLabCampOpenCapstonesRouteImport } from './routes/practicums_.startup-lab-camp.open-capstones'
import { Route as PracticumsStartupLabCampHowItWorksRouteImport } from './routes/practicums_.startup-lab-camp.how-it-works'
import { Route as PracticumsHanaroMarketingVoicesInMotionRouteImport } from './routes/practicums_.hanaro-marketing_.voices-in-motion'
import { Route as PracticumsStartupLabCampPracticumLeadershipTracksRouteImport } from './routes/practicums_.startup-lab-camp.practicum.leadership-tracks'
import { Route as PracticumsStartupLabCampPracticumCoachingProgramRouteImport } from './routes/practicums_.startup-lab-camp.practicum.coaching-program'
import { Route as PracticumsStartupLabCampCapstonesCapstoneIdRouteImport } from './routes/practicums_.startup-lab-camp.capstones.$capstoneId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeguardingRoute = SafeguardingRouteImport.update({
  id: '/safeguarding',
  path: '/safeguarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticumsRoute = PracticumsRouteImport.update({
  id: '/practicums',
  path: '/practicums',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowWithUsRoute = GrowWithUsRouteImport.update({
  id: '/grow-with-us',
  path: '/grow-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticumsStartupLabCampRoute =
  PracticumsStartupLabCampRouteImport.update({
    id: '/practicums_/startup-lab-camp',
    path: '/practicums/startup-lab-camp',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticumsMiraeIndustryRoute = PracticumsMiraeIndustryRouteImport.update({
  id: '/practicums_/mirae-industry',
  path: '/practicums/mirae-industry',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticumsHanaroRoute = PracticumsHanaroRouteImport.update({
  id: '/practicums_/hanaro',
  path: '/practicums/hanaro',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsDigitalMediaAndDroneShowTechnologyWithYanPaulDubbelmanRoute =
  NewsDigitalMediaAndDroneShowTechnologyWithYanPaulDubbelmanRouteImport.update({
    id: '/news_/digital-media-and-drone-show-technology-with-yan-paul-dubbelman',
    path: '/news/digital-media-and-drone-show-technology-with-yan-paul-dubbelman',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutSparkedRoute = AboutSparkedRouteImport.update({
  id: '/about_/sparked',
  path: '/about/sparked',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOurStoryRoute = AboutOurStoryRouteImport.update({
  id: '/about_/our-story',
  path: '/about/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticumsStartupLabCampIndexRoute =
  PracticumsStartupLabCampIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PracticumsStartupLabCampRoute,
  } as any)
const PracticumsStartupLabCampOpenCapstonesRoute =
  PracticumsStartupLabCampOpenCapstonesRouteImport.update({
    id: '/open-capstones',
    path: '/open-capstones',
    getParentRoute: () => PracticumsStartupLabCampRoute,
  } as any)
const PracticumsStartupLabCampHowItWorksRoute =
  PracticumsStartupLabCampHowItWorksRouteImport.update({
    id: '/how-it-works',
    path: '/how-it-works',
    getParentRoute: () => PracticumsStartupLabCampRoute,
  } as any)
const PracticumsHanaroMarketingVoicesInMotionRoute =
  PracticumsHanaroMarketingVoicesInMotionRouteImport.update({
    id: '/practicums_/hanaro-marketing_/voices-in-motion',
    path: '/practicums/hanaro-marketing/voices-in-motion',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticumsStartupLabCampPracticumLeadershipTracksRoute =
  PracticumsStartupLabCampPracticumLeadershipTracksRouteImport.update({
    id: '/practicum/leadership-tracks',
    path: '/practicum/leadership-tracks',
    getParentRoute: () => PracticumsStartupLabCampRoute,
  } as any)
const PracticumsStartupLabCampPracticumCoachingProgramRoute =
  PracticumsStartupLabCampPracticumCoachingProgramRouteImport.update({
    id: '/practicum/coaching-program',
    path: '/practicum/coaching-program',
    getParentRoute: () => PracticumsStartupLabCampRoute,
  } as any)
const PracticumsStartupLabCampCapstonesCapstoneIdRoute =
  PracticumsStartupLabCampCapstonesCapstoneIdRouteImport.update({
    id: '/capstones/$capstoneId',
    path: '/capstones/$capstoneId',
    getParentRoute: () => PracticumsStartupLabCampRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/grow-with-us': typeof GrowWithUsRoute
  '/news': typeof NewsRoute
  '/practicums': typeof PracticumsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/safeguarding': typeof SafeguardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/about/sparked': typeof AboutSparkedRoute
  '/news/digital-media-and-drone-show-technology-with-yan-paul-dubbelman': typeof NewsDigitalMediaAndDroneShowTechnologyWithYanPaulDubbelmanRoute
  '/practicums/hanaro': typeof PracticumsHanaroRoute
  '/practicums/mirae-industry': typeof PracticumsMiraeIndustryRoute
  '/practicums/startup-lab-camp': typeof PracticumsStartupLabCampRouteWithChildren
  '/practicums/hanaro-marketing/voices-in-motion': typeof PracticumsHanaroMarketingVoicesInMotionRoute
  '/practicums/startup-lab-camp/how-it-works': typeof PracticumsStartupLabCampHowItWorksRoute
  '/practicums/startup-lab-camp/open-capstones': typeof PracticumsStartupLabCampOpenCapstonesRoute
  '/practicums/startup-lab-camp/': typeof PracticumsStartupLabCampIndexRoute
  '/practicums/startup-lab-camp/capstones/$capstoneId': typeof PracticumsStartupLabCampCapstonesCapstoneIdRoute
  '/practicums/startup-lab-camp/practicum/coaching-program': typeof PracticumsStartupLabCampPracticumCoachingProgramRoute
  '/practicums/startup-lab-camp/practicum/leadership-tracks': typeof PracticumsStartupLabCampPracticumLeadershipTracksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/grow-with-us': typeof GrowWithUsRoute
  '/news': typeof NewsRoute
  '/practicums': typeof PracticumsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/safeguarding': typeof SafeguardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/about/our-story': typeof AboutOurStoryRoute
  '/about/sparked': typeof AboutSparkedRoute
  '/news/digital-media-and-drone-show-technology-with-yan-paul-dubbelman': typeof NewsDigitalMediaAndDroneShowTechnologyWithYanPaulDubbelmanRoute
  '/practicums/hanaro': typeof PracticumsHanaroRoute
  '/practicums/mirae-industry': typeof PracticumsMiraeIndustryRoute
  '/practicums/hanaro-marketing/voices-in-motion': typeof PracticumsHanaroMarketingVoicesInMotionRoute
  '/practicums/startup-lab-camp/how-it-works': typeof PracticumsStartupLabCampHowItWorksRoute
  '/practicums/startup-lab-camp/open-capstones': typeof PracticumsStartupLabCampOpenCapstonesRoute
  '/practicums/startup-lab-camp': typeof PracticumsStartupLabCampIndexRoute
  '/practicums/startup-lab-camp/capstones/$capstoneId': typeof PracticumsStartupLabCampCapstonesCapstoneIdRoute
  '/practicums/startup-lab-camp/practicum/coaching-program': typeof PracticumsStartupLabCampPracticumCoachingProgramRoute
  '/practicums/startup-lab-camp/practicum/leadership-tracks': typeof PracticumsStartupLabCampPracticumLeadershipTracksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connect': typeof ConnectRoute
  '/grow-with-us': typeof GrowWithUsRoute
  '/news': typeof NewsRoute
  '/practicums': typeof PracticumsRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/safeguarding': typeof SafeguardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/about_/our-story': typeof AboutOurStoryRoute
  '/about_/sparked': typeof AboutSparkedRoute
  '/news_/digital-media-and-drone-show-technology-with-yan-paul-dubbelman': typeof NewsDigitalMediaAndDroneShowTechnologyWithYanPaulDubbelmanRoute
  '/practicums_/hanaro': typeof PracticumsHanaroRoute
  '/practicums_/mirae-industry': typeof PracticumsMiraeIndustryRoute
  '/practicums_/startup-lab-camp': typeof PracticumsStartupLabCampRouteWithChildren
  '/practicums_/hanaro-marketing_/voices-in-motion': typeof PracticumsHanaroMarketingVoicesInMotionRoute
  '/practicums_/startup-lab-camp/how-it-works': typeof PracticumsStartupLabCampHowItWorksRoute
  '/practicums_/startup-lab-camp/open-capstones': typeof PracticumsStartupLabCampOpenCapstonesRoute
  '/practicums_/startup-lab-camp/': typeof PracticumsStartupLabCampIndexRoute
  '/practicums_/startup-lab-camp/capstones/$capstoneId': typeof PracticumsStartupLabCampCapstonesCapstoneIdRoute
  '/practicums_/startup-lab-camp/practicum/coaching-program': typeof PracticumsStartupLabCampPracticumCoachingProgramRoute
  '/practicums_/startup-lab-camp/practicum/leadership-tracks': typeof PracticumsStartupLabCampPracticumLeadershipTracksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/connect'
    | '/grow-with-us'
    | '/news'
    | '/practicums'
    | '/privacy'
    | '/refund-policy'
    | '/safeguarding'
    | '/sitemap.xml'
    | '/terms'
    | '/about/our-story'
    | '/about/sparked'
    | '/news/digital-media-and-drone-show-technology-with-yan-paul-dubbelman'
    | '/practicums/hanaro'
    | '/practicums/mirae-industry'
    | '/practicums/startup-lab-camp'
    | '/practicums/hanaro-marketing/voices-in-motion'
    | '/practicums/startup-lab-camp/how-it-works'
    | '/practicums/startup-lab-camp/open-capstones'
    | '/practicums/startup-lab-camp/'
    | '/practicums/startup-lab-camp/capstones/$capstoneId'
    | '/practicums/startup-lab-camp/practicum/coaching-program'
    | '/practicums/startup-lab-camp/practicum/leadership-tracks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/connect'
    | '/grow-with-us'
    | '/news'
    | '/practicums'
    | '/privacy'
    | '/refund-policy'
    | '/safeguarding'
    | '/sitemap.xml'
    | '/terms'
    | '/about/our-story'
    | '/about/sparked'
    | '/news/digital-media-and-drone-show-technology-with-yan-paul-dubbelman'
    | '/practicums/hanaro'
    | '/practicums/mirae-industry'
    | '/practicums/hanaro-marketing/voices-in-motion'
    | '/practicums/startup-lab-camp/how-it-works'
    | '/practicums/startup-lab-camp/open-capstones'
    | '/practicums/startup-lab-camp'
    | '/practicums/startup-lab-camp/capstones/$capstoneId'
    | '/practicums/startup-lab-camp/practicum/coaching-program'
    | '/practicums/startup-lab-camp/practicum/leadership-tracks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/connect'
    | '/grow-with-us'
    | '/news'
    | '/practicums'
    | '/privacy'
    | '/refund-policy'
    | '/safeguarding'
    | '/sitemap.xml'
    | '/terms'
    | '/about_/our-story'
    | '/about_/sparked'
    | '/news_/digital-media-and-drone-show-technology-with-yan-paul-dubbelman'
    | '/practicums_/hanaro'
    | '/practicums_/mirae-industry'
    | '/practicums_/startup-lab-camp'
    | '/practicums_/hanaro-marketing_/voices-in-motion'
    | '/practicums_/startup-lab-camp/how-it-works'
    | '/practicums_/startup-lab-camp/open-capstones'
    | '/practicums_/startup-lab-camp/'
    | '/practicums_/startup-lab-camp/capstones/$capstoneId'
    | '/practicums_/startup-lab-camp/practicum/coaching-program'
    | '/practicums_/startup-lab-camp/practicum/leadership-tracks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConnectRoute: typeof ConnectRoute
  GrowWithUsRoute: typeof GrowWithUsRoute
  NewsRoute: typeof NewsRoute
  PracticumsRoute: typeof PracticumsRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SafeguardingRoute: typeof SafeguardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AboutOurStoryRoute: typeof AboutOurStoryRoute
  AboutSparkedRoute: typeof AboutSparkedRoute
  NewsDigitalMediaAndDroneShowTechnologyWithYanPaulDubbelmanRoute: typeof NewsDigitalMediaAndDroneShowTechnologyWithYanPaulDubbelmanRoute
  PracticumsHanaroRoute: typeof PracticumsHanaroRoute
  PracticumsMiraeIndustryRoute: typeof PracticumsMiraeIndustryRoute
  PracticumsStartupLabCampRoute: typeof PracticumsStartupLabCampRouteWithChildren
  PracticumsHanaroMarketingVoicesInMotionRoute: typeof PracticumsHanaroMarketingVoicesInMotionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safeguarding': {
      id: '/safeguarding'
      path: '/safeguarding'
      fullPath: '/safeguarding'
      preLoaderRoute: typeof SafeguardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicums': {
      id: '/practicums'
      path: '/practicums'
      fullPath: '/practicums'
      preLoaderRoute: typeof PracticumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grow-with-us': {
      id: '/grow-with-us'
      path: '/grow-with-us'
      fullPath: '/grow-with-us'
      preLoaderRoute: typeof GrowWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicums_/startup-lab-camp': {
      id: '/practicums_/startup-lab-camp'
      path: '/practicums/startup-lab-camp'
      fullPath: '/practicums/startup-lab-camp'
      preLoaderRoute: typeof PracticumsStartupLabCampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicums_/mirae-industry': {
      id: '/practicums_/mirae-industry'
      path: '/practicums/mirae-industry'
      fullPath: '/practicums/mirae-industry'
      preLoaderRoute: typeof PracticumsMiraeIndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicums_/hanaro': {
      id: '/practicums_/hanaro'
      path: '/practicums/hanaro'
      fullPath: '/practicums/hanaro'
      preLoaderRoute: typeof PracticumsHanaroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/digital-media-and-drone-show-technology-with-yan-paul-dubbelman': {
      id: '/news_/digital-media-and-drone-show-technology-with-yan-paul-dubbelman'
      path: '/news/digital-media-and-drone-show-technology-with-yan-paul-dubbelman'
      fullPath: '/news/digital-media-and-drone-show-technology-with-yan-paul-dubbelman'
      preLoaderRoute: typeof NewsDigitalMediaAndDroneShowTechnologyWithYanPaulDubbelmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/sparked': {
      id: '/about_/sparked'
      path: '/about/sparked'
      fullPath: '/about/sparked'
      preLoaderRoute: typeof AboutSparkedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/our-story': {
      id: '/about_/our-story'
      path: '/about/our-story'
      fullPath: '/about/our-story'
      preLoaderRoute: typeof AboutOurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicums_/startup-lab-camp/': {
      id: '/practicums_/startup-lab-camp/'
      path: '/'
      fullPath: '/practicums/startup-lab-camp/'
      preLoaderRoute: typeof PracticumsStartupLabCampIndexRouteImport
      parentRoute: typeof PracticumsStartupLabCampRoute
    }
    '/practicums_/startup-lab-camp/open-capstones': {
      id: '/practicums_/startup-lab-camp/open-capstones'
      path: '/open-capstones'
      fullPath: '/practicums/startup-lab-camp/open-capstones'
      preLoaderRoute: typeof PracticumsStartupLabCampOpenCapstonesRouteImport
      parentRoute: typeof PracticumsStartupLabCampRoute
    }
    '/practicums_/startup-lab-camp/how-it-works': {
      id: '/practicums_/startup-lab-camp/how-it-works'
      path: '/how-it-works'
      fullPath: '/practicums/startup-lab-camp/how-it-works'
      preLoaderRoute: typeof PracticumsStartupLabCampHowItWorksRouteImport
      parentRoute: typeof PracticumsStartupLabCampRoute
    }
    '/practicums_/hanaro-marketing_/voices-in-motion': {
      id: '/practicums_/hanaro-marketing_/voices-in-motion'
      path: '/practicums/hanaro-marketing/voices-in-motion'
      fullPath: '/practicums/hanaro-marketing/voices-in-motion'
      preLoaderRoute: typeof PracticumsHanaroMarketingVoicesInMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicums_/startup-lab-camp/practicum/leadership-tracks': {
      id: '/practicums_/startup-lab-camp/practicum/leadership-tracks'
      path: '/practicum/leadership-tracks'
      fullPath: '/practicums/startup-lab-camp/practicum/leadership-tracks'
      preLoaderRoute: typeof PracticumsStartupLabCampPracticumLeadershipTracksRouteImport
      parentRoute: typeof PracticumsStartupLabCampRoute
    }
    '/practicums_/startup-lab-camp/practicum/coaching-program': {
      id: '/practicums_/startup-lab-camp/practicum/coaching-program'
      path: '/practicum/coaching-program'
      fullPath: '/practicums/startup-lab-camp/practicum/coaching-program'
      preLoaderRoute: typeof PracticumsStartupLabCampPracticumCoachingProgramRouteImport
      parentRoute: typeof PracticumsStartupLabCampRoute
    }
    '/practicums_/startup-lab-camp/capstones/$capstoneId': {
      id: '/practicums_/startup-lab-camp/capstones/$capstoneId'
      path: '/capstones/$capstoneId'
      fullPath: '/practicums/startup-lab-camp/capstones/$capstoneId'
      preLoaderRoute: typeof PracticumsStartupLabCampCapstonesCapstoneIdRouteImport
      parentRoute: typeof PracticumsStartupLabCampRoute
    }
  }
}

interface PracticumsStartupLabCampRouteChildren {
  PracticumsStartupLabCampHowItWorksRoute: typeof PracticumsStartupLabCampHowItWorksRoute
  PracticumsStartupLabCampOpenCapstonesRoute: typeof PracticumsStartupLabCampOpenCapstonesRoute
  PracticumsStartupLabCampIndexRoute: typeof PracticumsStartupLabCampIndexRoute
  PracticumsStartupLabCampCapstonesCapstoneIdRoute: typeof PracticumsStartupLabCampCapstonesCapstoneIdRoute
  PracticumsStartupLabCampPracticumCoachingProgramRoute: typeof PracticumsStartupLabCampPracticumCoachingProgramRoute
  PracticumsStartupLabCampPracticumLeadershipTracksRoute: typeof PracticumsStartupLabCampPracticumLeadershipTracksRoute
}

const PracticumsStartupLabCampRouteChildren: PracticumsStartupLabCampRouteChildren =
  {
    PracticumsStartupLabCampHowItWorksRoute:
      PracticumsStartupLabCampHowItWorksRoute,
    PracticumsStartupLabCampOpenCapstonesRoute:
      PracticumsStartupLabCampOpenCapstonesRoute,
    PracticumsStartupLabCampIndexRoute: PracticumsStartupLabCampIndexRoute,
    PracticumsStartupLabCampCapstonesCapstoneIdRoute:
      PracticumsStartupLabCampCapstonesCapstoneIdRoute,
    PracticumsStartupLabCampPracticumCoachingProgramRoute:
      PracticumsStartupLabCampPracticumCoachingProgramRoute,
    PracticumsStartupLabCampPracticumLeadershipTracksRoute:
      PracticumsStartupLabCampPracticumLeadershipTracksRoute,
  }

const PracticumsStartupLabCampRouteWithChildren =
  PracticumsStartupLabCampRoute._addFileChildren(
    PracticumsStartupLabCampRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConnectRoute: ConnectRoute,
  GrowWithUsRoute: GrowWithUsRoute,
  NewsRoute: NewsRoute,
  PracticumsRoute: PracticumsRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SafeguardingRoute: SafeguardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AboutOurStoryRoute: AboutOurStoryRoute,
  AboutSparkedRoute: AboutSparkedRoute,
  NewsDigitalMediaAndDroneShowTechnologyWithYanPaulDubbelmanRoute:
    NewsDigitalMediaAndDroneShowTechnologyWithYanPaulDubbelmanRoute,
  PracticumsHanaroRoute: PracticumsHanaroRoute,
  PracticumsMiraeIndustryRoute: PracticumsMiraeIndustryRoute,
  PracticumsStartupLabCampRoute: PracticumsStartupLabCampRouteWithChildren,
  PracticumsHanaroMarketingVoicesInMotionRoute:
    PracticumsHanaroMarketingVoicesInMotionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
